# add values for the following secrets
# then rename this file to secrets.toml
# then place it under .streamlit/ See url for details:
# https://docs.streamlit.io/deploy/streamlit-community-cloud/deploy-your-app/secrets-management#use-secrets-in-your-app

# Retrievable from Snowsight after creating Snowflake account
SNOWFLAKE_USER = ''
SNOWFLAKE_PASSWORD = ''
SNOWFLAKE_ACCOUNT = ''

# https://dictionaryapi.com/products/api-spanish-dictionary
MERRIAM_WEBSTER_API_KEY = ''

# https://console.cloud.google.com/marketplace/product/google/texttospeech.googleapis.com
GCP_TTS_API_KEY = ''
