# add your own secrets then rename this file to secrets.toml (ie remove `example_` prefix)
SNOWFLAKE_USER = ''
SNOWFLAKE_PASSWORD = ''
SNOWFLAKE_ACCOUNT = ''
MERRIAM_WEBSTER_API_KEY = ''
GCP_TTS_API_KEY = ''
